dist: trusty

language: java

notifications:
 email: false

jdk:
 - oraclejdk8

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

before_script:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls

